# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dog tinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for dog tinder
  pod 'GoogleSignIn'
  target 'dog tinderTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'GoogleSignIn'
  end

end
